"""init commit

Revision ID: 473b686298b3
Revises: 
Create Date: 2026-03-09 20:24:46.684148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '473b686298b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FIELDS',
    sa.Column('field_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('field_id'),
    sa.UniqueConstraint('field_name')
    )
    op.create_table('KEYWORDS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['KEYWORDS.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    op.create_table('LEVEL_THRESHOLDS',
    sa.Column('level_name', sa.String(), nullable=False),
    sa.Column('min_post', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('level_name')
    )
    op.create_table('PLATFORM',
    sa.Column('platform_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('platform_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('USER',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('color_theme', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('notify_email', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('AUTH_USER',
    sa.Column('auth_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USER.user_id'], ),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('EXTERNAL_POSTS',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_analyzed', sa.Boolean(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['FIELDS.field_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_EXTERNAL_POSTS_category'), 'EXTERNAL_POSTS', ['category'], unique=False)
    op.create_index(op.f('ix_EXTERNAL_POSTS_field_id'), 'EXTERNAL_POSTS', ['field_id'], unique=False)
    op.create_index(op.f('ix_EXTERNAL_POSTS_is_analyzed'), 'EXTERNAL_POSTS', ['is_analyzed'], unique=False)
    op.create_index(op.f('ix_EXTERNAL_POSTS_published_at'), 'EXTERNAL_POSTS', ['published_at'], unique=False)
    op.create_table('POSTS',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['FIELDS.field_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['PLATFORM.platform_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['USER.user_id'], ),
    sa.PrimaryKeyConstraint('url', 'user_id', 'platform_id')
    )
    op.create_table('USER_FIELDS',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['FIELDS.field_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['USER.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'field_id')
    )
    op.create_table('USER_PLATFORM',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=255), nullable=True),
    sa.Column('last_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['PLATFORM.platform_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['USER.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'platform_id')
    )
    op.create_table('EXTERNAL_POSTS_KEYWORDS',
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['KEYWORDS.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['EXTERNAL_POSTS.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('keyword_id', 'post_id')
    )
    op.create_table('POST_KEYWORDS',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['KEYWORDS.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['url', 'user_id', 'platform_id'], ['POSTS.url', 'POSTS.user_id', 'POSTS.platform_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('url', 'user_id', 'platform_id', 'keyword_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('POST_KEYWORDS')
    op.drop_table('EXTERNAL_POSTS_KEYWORDS')
    op.drop_table('USER_PLATFORM')
    op.drop_table('USER_FIELDS')
    op.drop_table('POSTS')
    op.drop_index(op.f('ix_EXTERNAL_POSTS_published_at'), table_name='EXTERNAL_POSTS')
    op.drop_index(op.f('ix_EXTERNAL_POSTS_is_analyzed'), table_name='EXTERNAL_POSTS')
    op.drop_index(op.f('ix_EXTERNAL_POSTS_field_id'), table_name='EXTERNAL_POSTS')
    op.drop_index(op.f('ix_EXTERNAL_POSTS_category'), table_name='EXTERNAL_POSTS')
    op.drop_table('EXTERNAL_POSTS')
    op.drop_table('AUTH_USER')
    op.drop_table('USER')
    op.drop_table('PLATFORM')
    op.drop_table('LEVEL_THRESHOLDS')
    op.drop_table('KEYWORDS')
    op.drop_table('FIELDS')
    # ### end Alembic commands ###
