"""add widget_id

Revision ID: a84d3e33bf72
Revises: 473b686298b3
Create Date: 2026-03-12 15:51:46.528039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a84d3e33bf72'
down_revision: Union[str, Sequence[str], None] = '473b686298b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER', sa.Column('widget_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USER', 'widget_id')
    # ### end Alembic commands ###
